### ISSUE TITLE
无法记录bot发送的消息

### ISSUE THREAD

**Issue by kexue-z** [thereisnodice/TRPGLogger#1]
nonebot2 2.0.0a15
go-cqhttp v1.0.0-beta6
nonebot-plugin-trpglogger  0.2.0

已在gocq中开启`report-self-message: true`
且在nonebot2的logs中可以看到上报信息

报错如下：
```
08-16 20:03:13 [SUCCESS] nonebot | CQHTTP 1505856729 | [message_sent]: {'time': 1629115393, 'self_id': 1505856729, 'post_type': 'message_sent', 'sender': {'age': 0, 'area': '', 'card': '', 'level': '', 'nickname': '岛島岛島岛島风～', 'role': 'owner', 'sex': 'unknown', 'title': '', 'user_id': 1505856729}, 'message': '1次投掷：D100=78', 'message_type': 'group', 'font': 0, 'raw_message': '1次投掷：D100=78', 'group_id': 363342330, 'message_id': -65498130, 'user_id': 1505856729, 'anonymous': None, 'sub_type': 'normal', 'message_seq': 1394}
08-16 20:03:13 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_trpglogger, type=message_sent, priority=1, temp=False>
08-16 20:03:13 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_trpglogger, type=message_sent, priority=1, temp=False> running complete
08-16 20:03:13 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_trpglogger, type=message_sent, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_trpglogger/__init__.py", line 54, in get_message
    return event.get_plaintext()
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/cqhttp/event.py", line 48, in get_plaintext
    raise ValueError("Event has no message!")
ValueError: Event has no message!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nonebot/bot.py", line 31, in <module>
    nonebot.run(app="bot:app")
  File "/usr/local/lib/python3.9/site-packages/nonebot/__init__.py", line 277, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 215, in run
    uvicorn.run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 393, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 50, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 127, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 155, in _run_matcher
    await matcher.run(bot, event, state)
  File "/usr/local/lib/python3.9/site-packages/nonebot/matcher.py", line 584, in run
    await handler(self, bot, event, self.state)
  File "/usr/local/lib/python3.9/site-packages/nonebot/handler.py", line 81, in __call__
    await self.func(
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_trpglogger/__init__.py", line 17, in _
    message=get_message(event)
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_trpglogger/__init__.py", line 56, in get_message
    return event.message[0]["data"]["text"]
TypeError: string indices must be integers
```

**Comment by j1g5awi** [comment]
目前还有这个问题吗？我最近才抽出空来更新这个插件。

**Comment by kexue-z** [comment]
刚刚用了最新的更新 还是报错...
具体如下:
# 开始记录
qq发送 `log on`
然后就报错...
```
09-19 23:11:07 [SUCCESS] nonebot | CQHTTP 15xxx729 | [message_sent]: {'time': 1632064267, 'self_id': 1505xxx29, 'post_type': 'message_sent', 'font': 0, 'message_seq': 296094, 'anonymous': None, 'sender': {'age': 0, 'area': '', 'card': '屑岛风bot', 'level': '', 'nickname': '岛島岛島岛島风～', 'role': 'member', 'sex': 'unknown', 'title': '', 'user_id': 15xxxxx9}, 'user_id': 150xxxxx29, 'message_id': 204xxx722, 'message': '开始日志记录', 'message_type': 'group', 'raw_message': '开始日志记录', 'sub_type': 'normal', 'group_id': 7xxx7}
09-19 23:11:07 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_trpglogger, type=message_sent, priority=1, temp=False>
09-19 23:11:07 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_trpglogger, type=message, priority=1, temp=False> running complete
09-19 23:11:07 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_trpglogger, type=message_sent, priority=1, temp=False> running complete
09-19 23:11:07 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_trpglogger, type=message_sent, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "/nonebot/bot.py", line 30, in <module>
    nonebot.run(app="bot:app")
  File "/usr/local/lib/python3.9/site-packages/nonebot/__init__.py", line 277, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 215, in run
    uvicorn.run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 393, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 50, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 127, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 155, in _run_matcher
    await matcher.run(bot, event, state)
  File "/usr/local/lib/python3.9/site-packages/nonebot/matcher.py", line 584, in run
    await handler(self, bot, event, self.state)
  File "/usr/local/lib/python3.9/site-packages/nonebot/handler.py", line 81, in __call__
    await self.func(
  File "/nonebot/plugins/nonebot_plugin_trpglogger/__init__.py", line 60, in _
    message = event.message[0]["data"]["text"]
TypeError: string indices must be integers
```
此后别人发的消息正常没有报错
但是bot自己发送的消息后也会出现上述报错

# 最后上传
使用`log off` 指令 后 bot 发送 `正在上传文件，请稍等`后同样报错
最后返回 `上传已完成，请访问 https://logpainter.kokona.tech/?s3=group_707xxxx6.txt 以查看记录`

检查结果 发现并没有记录发送的指令 如 `.rd`等 和bot发送的消息
但是却记录了最后发送的指令 `log off`
